version: '3.8'
services:
  database:
    container_name: meddly-database
    image: postgres:latest
    restart: 'always'
    environment:
      POSTGRES_USER: 'meddly'
      POSTGRES_PASSWORD: 'meddly'
      POSTGRES_DB: 'app'
    ports:
      - "11000:5432"
  app:
    container_name: meddly-backend
    build: .
    restart: always
    depends_on:
      - database
    stdin_open: true
    tty: true
    ports:
      - "11001:8000"
    volumes:
      - .:/app
    command: python app.py
